export const REGEISTER_REQUEST="REGEISTER_REQUEST"
export const REGEISTER_SUCCESS="REGEISTER_SUCCESS"
export const REGEISTER_FALIURE="REGEISTER_FALIURE"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FALIURE="LOGIN_FALIURE"

export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FALIURE="GET_USER_FALIURE"

export const LOGOUT="LOGOUT";